[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "xscope-fileio"
version = "1.3.0"
description = "Python module for managing files using xscope"
authors = ["XMOS"]
license = "LICENSE.rst"
readme = "README.rst"
homepage = "https://github.com/xmos/xscope_fileio"
packages = [
    { include = "xscope_fileio" },
    { include = "host", to = "xscope_fileio"},
]
build = "host/build_host.py"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "1.26.4"
