[build-system]
requires = ["flit_core >=3.8,<4"]
build-backend = 'flit_core.buildapi'

[project]
name = "xscope_fileio"
description = "Python module for reading and writing files using xscope"
version = "1.3.0"
authors = [{name = "XMOS"}]
readme = "README.rst"
license = {file = "LICENSE.rst"}

[project.urls]
Home = "https://github.com/xmos/xscope_fileio"

[tool.flit.sdist]
include = ["host/"]
