[build-system]
requires = ["setuptools >= 75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xscope-fileio"
version = "1.3.0"
description = "Python module for managing files using xscope"
authors = [{name = "XMOS"}]
license = {file = "LICENSE.rst"}
readme = "README.rst"
requires-python = ">=3.10"
dependencies = ["numpy>=1.26.4"]
classifiers = [""]

[project.urls]
Homepage = "https://github.com/xmos/xscope_fileio"

[tool.setuptools]
packages = ["xscope_fileio", "host"]
